services:
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - api
  api:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: avaliacaofilmes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: