server:
  port: ${PORT:8080}

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://postgres:5432/avaliacaofilmes
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  sql:
    init:
      schema-locations: classpath:/schema-postgresql.sql
      mode: always
      platform: postgressss